on:
  push:
    tags:
      - 'v*-beta'

name: Pre-Release

jobs:
  build:
    name: Create Pre-Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Version From Tag
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Module
        run: npm run release

      - name: Prepare dist files
        run: cp README.md LICENSE dist/

      - name: Modify Module Manifest With Release-Specific Values
        uses: microsoft/variable-substitution@v1
        with:
          files: './dist/module.json'
        env:
          version: ${{steps.get_version.outputs.version-without-v}}
          url: https://github.com/${{github.repository}}
          manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
          download: https://github.com/${{github.repository}}/releases/download/${{steps.get_version.outputs.version}}/module.zip
          bugs: https://github.com/${{github.repository}}/issues

      - name: Zip files
        run: |
          cd dist/
          zip -r module.zip module.json README.md LICENSE languages/ scripts/ packs/

      - name: Update Release with Files
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Pre-Release ${{steps.get_version.outputs.version}}
          draft: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './dist/module.json, ./dist/module.zip'
          tag: ${{ github.ref }}
